version: 2

updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
      day: saturday
      time: '04:00'
      timezone: America/Chicago
    commit-message:
      prefix: 'Chore [deps:gomod]'

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: sunday
      time: '04:00'
      timezone: America/Chicago
    commit-message:
      prefix: 'Chore [deps:github-actions]'
