before:
  hooks:
    - go mod tidy -compat=1.18
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
    goarm:
      - "5"
      - "6"
      - "7"
    main: ./cmd/mydyndns
    binary: mydyndns
    ldflags:
      - -s -w -X {{.ModulePath}}/cmd/mydyndns/cli.Version={{.Version}}
        -X main.commit={{.Commit}}
        -X main.date={{.Date}}
        -X main.builtBy=goreleaser
archives:
  - format_overrides:
      - goos: windows
        format: zip

dockers:
  - image_templates:
      - "{{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:{{ .Tag }}"
      - "{{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:v{{ .Major }}"
      - "{{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:v{{ .Major }}.{{ .Minor }}"
      - "{{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:latest"
    dockerfile: goreleaser.Dockerfile
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--label=org.opencontainers.image.description={{.ReleaseNotes}}"
      - "--platform=linux/amd64"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^test:'
