name: Test
on:
  - push
  - pull_request
jobs:
  test:
    name: Test
    strategy:
      matrix:
        platform:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{matrix.platform}}
    steps:
      - id: go-cache-paths
        run: |
          echo "::set-output name=go-build::$(go env GOCACHE)"
          echo "::set-output name=go-mod::$(go env GOMODCACHE)"

      - name: Check out code into the Go module directory
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          show-progress: false
          persist-credentials: false

      - name: Set up Go ${{matrix.go-version}}
        uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed # v5.1.0
        with:
          go-version-file: go.mod

      - name: Test with Reporting (Linux only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          go test -race -covermode=atomic -coverprofile=cover.out ./...
          go test -race -covermode=atomic -coverprofile=cover.out -json ./... > report.json

      - name: Test without Reporting (non-Linux only)
        if: matrix.platform != 'ubuntu-latest'
        run: go test -race ./...
